### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by quantumlicht** [mcamac/react-text-annotate#2]
Hello, thanks for contributing this code!

I plan on using it for a demo. Seeing your example, I cannot quite understand the difference between
`TextAnnotator` and `TokenAnnotator` Do you mind explaining and/or adding some documentation around this?

Thanks!

**Comment by mcamac** [comment]
Great idea, will add and ping you when it’s there!

**Comment by guillaumedsde** [comment]
Hi, kindly bumping this issue :)

**Comment by mcamac** [comment]
Hi, thanks for the bump -- I should get this to some time this week (also cleaning up and modernizing the package a little bit!).

**Comment by mcamac** [comment]
Working in #5

**Comment by guillaumedsde** [comment]
Much appreciated :)

**Comment by mcamac** [comment]
Hi all, released v0.2.0 (React 16.8+), and [docs for both annotators](https://mcamac.github.io/react-text-annotate/annotators#textannotator)
