### ISSUE TITLE
[Question] Token position based on character position

### ISSUE THREAD

**Issue by Akshay090** [mcamac/react-text-annotate#7]
Is it possible to do annotate based on character position as currently, we do based on word position in start and end

**Comment by mcamac** [comment]
Just released v0.2.0 with docs - check out [TextAnnotator](https://mcamac.github.io/react-text-annotate/annotators#textannotator). Let me know if that works for your use case?

**Comment by Akshay090** [comment]
Thanks it helped, you are a life saver :1st_place_medal:
